services:

  dados_estoque:
    image: postgres:15-alpine
    container_name: dados_estoque
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estoque
    networks:
      - manager
    volumes:
      - estoque_data:/var/lib/postgresql/data
      - ./init-resources:/docker-entrypoint-initdb.d:ro
    restart: always

  dados_vendas:
    image: postgres:15-alpine
    container_name: dados_vendas
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vendas
    networks:
      - manager
    volumes:
      - ./init-resources:/docker-entrypoint-initdb.d:ro
      - vendas_data:/var/lib/postgresql/data
    restart: always

  dados_rh:
    image: postgres:15-alpine
    container_name: dados_rh
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rh
    networks:
      - manager
    volumes:
      - ./init-resources/rh.sql:/docker-entrypoint-initdb.d/rh.sql:ro
      - rh_data:/var/lib/postgresql/data
    restart: always

  estoque:
    image: estoque:latest
    container_name: estoque
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - manager
    restart: always

networks:
  manager:
    driver: bridge

volumes:
  vendas_data:
  estoque_data:
  rh_data:
  manager_data: