syntax = "proto3";

option java_package = "com.manager.estoque";
option java_multiple_files = false;
option java_outer_classname = "EstoqueProto";

service EstoqueService {
    rpc ConsultarEstoque(ConsultaEstoqueRequest) returns (EstoqueResponse);
    rpc AtualizarEstoque(AtualizaEstoqueRequest) returns (EstoqueResponse);
    rpc ListarTodosEstoques(ListaEstoquesRequest) returns (ListaEstoquesResponse);
}

message ConsultaEstoqueRequest {
    int32 produto_id = 1;
}


message AtualizaEstoqueRequest {
    int32 produto_id = 1;
    int32 quantidade = 2;
    string operacao = 3;
}

message ListaEstoquesRequest {
    // Pode adicionar parâmetros de filtro aqui, se necessário
}

message ListaEstoquesResponse {
    repeated EstoqueResponse produtos = 1;
    int32 total_produtos = 2;
    bool sucesso = 3;
    string mensagem = 4;
}

message EstoqueResponse {
    int32 produto_id = 1;
    string nome = 2;
    int32 quantidade = 3;
    double preco = 4;
    string status = 5;
    bool sucesso = 6;
    string mensagem = 7;
}