grpc.server.port=9092
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5433/vendas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate=ERROR

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Para debug
logging.level.org.springdoc=DEBUG
